### ISSUE TITLE
Monitoring epic, v3

### ISSUE THREAD

**Issue by darkk** [ooni/backend#243]
- [ ] monitor `Oops` and `BUG:` in kernel log ooni/sysadmin#210
- [ ] add regexp for go app crashes in systemd syslog ooni/sysadmin#220
- [ ] monitor nginx error.log ooni/sysadmin#138
- [ ] monitor public endpoints with non-trivial health check ooni/sysadmin#113 ooni/sysadmin#173 ooni/sysadmin#194 https://github.com/ooni/sysadmin/pull/277#issuecomment-469057510
- [ ] monitor public webservice health check from another prometheus ooni/sysadmin#174 
- [ ] monitor all network endpoints with blackbox checks -- 373600887c24eab683d3e918fb45b33cd1d720a6
- [ ] postgres replica latency ooni/sysadmin#240 
- [ ] anonymize IPv4 address to /24 and IPv6 to /48 (min routable prefix: [1](https://nsrc.org/workshops/2016/apricot2016/raw-attachment/wiki/Track2BGP/05-BGP-BCP.pdf), [2](https://www.enog.org/wp-content/uploads/presentations/enog-14/4-IPv6-BGP-Tutorial.pdf) while sou, ) -- 7b12322deb8d217e3ad37d6faea14f8d796a20f8, ea1f6a4826f537b9b725c39800c522a666714cc4
- [ ] use [dockerd monitoring](https://docs.docker.com/config/thirdparty/prometheus/) to track fast restarts with `engine_daemon_container_actions_seconds_count{action="start"}` ooni/sysadmin#220
- [ ] monitor number of systemd service restarts-per-minute (needs node_exporter >0.16.0)
