### ISSUE TITLE
Upgrade the database hosts: move to a new DB host in AMS

### ISSUE THREAD

**Issue by hellais** [ooni/backend#263]
Setup AMS-PG

We should also consider if it makes sense to upgrade from postgres 9 to postgres 11.

**Comment by hellais** [comment]
We discussed that as part of this we should look into updating to postgresql 12

**Comment by FedericoCeratto** [comment]
TODO:
- [ ] Setup new AMS db 
- [ ] Rsync live datadir from HKG
- [ ] Try pg_upgrade
- [ ] Rsync datadir from HKG while stopped
- [ ] Run pg_upgrade again
- [ ] Test API and fastpath against new AMS db
