### ISSUE TITLE
Migration to backend-fsn / Clickhouse

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/backend#549]
This is a **roadmap** to switch the API+DB host from ams-pg to backend-fsn.
We expect to benefit from: faster storage, more efficient (columnar) database Clickhouse, more efficient disk space usage, cheaper hosting.
Secondary goals: reduce number of DB tables, reduce ops workload. Allow better feature extraction in fastpath and more feature-rich MAT. Move towards fault-tolerant (active/active) architecture.

- [x] Run ams-pg-test as testbed for the new codebase
- [x] Setup continuous sync of fastpath and jsonl tables from ams-pg to fsn. 
  - [x] Setup monitoring for differences
- [x] Fix missing domain column on fastpath table on fsn
- [x] Forward read-only API calls from Nginx on ams-pg to fsn 
- [x] Forward test-list/prioritization CRUD API calls from Nginx on ams-pg to fsn. Msmt submission stays on ams-pg
- [x] Run in such configuration for a long bake-in period
- [x] Switch msmt submission to fsn using Nginx forwarding
  - [x] Monitor ams-pg for any network traffic
- [x] Switch DNS entries to use fsn only
- [ ] Shut down ams-pg
