### ISSUE TITLE
fastpath: add support for richer feature extraction

### ISSUE THREAD

**Issue by hellais** [ooni/backend#593]
Extract additional features in the fastpath to make data analysis more powerful and the detection of censorship events more accurate.

A document which outlines some of the features we are interested in extracting can be found here: https://docs.google.com/document/d/1OI5msLwHkCFRsDBvdtUxSU7kelWiBlMFZ_TN2mcH7NE

- [ ] Extract more features
- [ ] Add 2-level classification e.g. DNS->nxdomain
- [ ] Add new columns to DB table
- [x] Modify fastpath or reprocessor to reprocess new msmts
- [ ] Perform table optimize to remove duplicates 

The longer term plan is documented here: https://docs.google.com/document/d/1ahQRGQu7ASYmPjRwcRfXiQoDfk8YoMCm2IG-G8UzeJY/edit#heading=h.46xa7il1athv

**Comment by hellais** [comment]
This is mostly superseeded by the observation tables in ooni/data: https://github.com/ooni/data/pull/15

**Comment by hellais** [comment]
WRT to ISOC this is completed.
