### ISSUE TITLE
Make plan for future of OONI infrastructure

### ISSUE THREAD

**Issue by hellais** [ooni/backend#785]
We currently have a variety of different deployment patterns for different parts of OONI infrastructure. The patterns we are currently using are not easily adaptable to fit the use case of all the needs and some of these patterns are quite cumbersome and complex to manage.

The primary focus of this will be frontend components, but we will also consider using this for backend components too further down the line.

The goal of this epic is to sketch out a plan for the future of this.

Plan of action:
* [x] Write a design document outlining the scope of the problem
* [x] Define the requirements of the solution 
* [x] Make a list of solutions to evaluate
* [ ] Create survey to collect requirements and painpoints from team members
* [ ] Setup an account on all the platforms and try deploying some of our infrastructure on it to see how it goes
    * [x] Railway
    * [x] Render.com
    * [ ] Fly.io (WIP)
    * ~qovery~ broken and very bad onboarding. Will not spend more time trying to sign up for an account.
    * [x] Terraform platform
    * [ ] Spacelift
    * [x] Datadog
* [ ] Pick a solution and move forward with execution

More details can be found in this doc: https://docs.google.com/document/d/10YnG3wAmncU7Ucp1zwif7bpyA9vOuuq7XoI9S9LYCys/edit

**Comment by hellais** [comment]
I would say we have a plan. It's outlined in the future of OONI Infrastructure document and presented during the future of OONI Infrastructure internal presentation.

We can consider this done.
