### ISSUE TITLE
Port Tier 1 backend/legacyapi components over to the ooniapi services pattern

### ISSUE THREAD

**Issue by jbonisteel** [ooni/backend#867]
Tier 1 (Essential) components

- [ ]  OONI API measurement listing
- [x]  OONI Explorer
- [x]  OONI Run
- [x]  OONI Data analysis pipeline
- [x]  OONI Findings API
- [x]  Website analytics
- [ ]  OONI.org website
